// Package emitter renders generated Go source files from the binding model.
package emitter

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/bnema/purego-pipewire/cmd/pipewiregen/internal/model"
)

// Emit generates Go source files from the model and writes them to the root directory.
// It returns a map of generated file paths to their content.
func Emit(m *model.Model, root string) (map[string][]byte, error) {
	out := make(map[string][]byte)
	for _, group := range m.Groups {
		capiPath := filepath.Join("internal", "capi", group.Name+"_gen.go")
		portPath := filepath.Join("internal", "ports", "out", group.Name+"_gen.go")

		capiContent, err := renderCAPI(group, m.Symbols, m.Libraries)
		if err != nil {
			return nil, fmt.Errorf("render capi for group %q: %w", group.Name, err)
		}
		out[capiPath] = capiContent

		portContent, err := renderPort(group, m.Symbols)
		if err != nil {
			return nil, fmt.Errorf("render port for group %q: %w", group.Name, err)
		}
		out[portPath] = portContent
	}
	return out, writeAll(root, out)
}

// renderCAPI generates the raw C API function types and registration helpers.
func renderCAPI(group model.Group, symbols []model.Symbol, libraries []model.Library) ([]byte, error) {
	// Find symbols belonging to this group
	groupSymbols := filterSymbolsByGroup(symbols, group.Name)

	// Build library map for lookup
	libMap := make(map[string]string)
	for _, lib := range libraries {
		libMap[lib.Name] = lib.SOName
	}

	data := struct {
		Group      model.Group
		Symbols    []model.Symbol
		LibraryMap map[string]string
	}{
		Group:      group,
		Symbols:    groupSymbols,
		LibraryMap: libMap,
	}

	tmpl, err := template.New("capi").Funcs(template.FuncMap{
		"title": strings.Title,
	}).Parse(capiTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderPort generates the outbound interface definitions.
func renderPort(group model.Group, symbols []model.Symbol) ([]byte, error) {
	groupSymbols := filterSymbolsByGroup(symbols, group.Name)

	// Convert symbols to methods with proper Go names
	type Method struct {
		Name      string
		GoName    string
		Signature string
		CName     string
	}

	methods := make([]Method, 0, len(groupSymbols))
	for _, sym := range groupSymbols {
		methods = append(methods, Method{
			Name:      sym.Name,
			GoName:    toGoName(sym.Name),
			Signature: sym.Signature,
			CName:     sym.Name,
		})
	}

	data := struct {
		Group   model.Group
		Methods []Method
	}{
		Group:   group,
		Methods: methods,
	}

	tmpl, err := template.New("port").Funcs(template.FuncMap{
		"title": strings.Title,
	}).Parse(portTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// filterSymbolsByGroup returns symbols that belong to the given group.
func filterSymbolsByGroup(symbols []model.Symbol, groupName string) []model.Symbol {
	var result []model.Symbol
	for _, sym := range symbols {
		if sym.Group == groupName {
			result = append(result, sym)
		}
	}
	return result
}

// toGoName converts a C function name like pw_init to a Go name like PWInit.
func toGoName(cName string) string {
	// Handle pw_ prefix specially
	if strings.HasPrefix(cName, "pw_") {
		name := cName[3:]
		parts := strings.Split(name, "_")
		for i, p := range parts {
			parts[i] = strings.Title(p)
		}
		return "PW" + strings.Join(parts, "")
	}
	// Generic conversion
	parts := strings.Split(cName, "_")
	for i, p := range parts {
		parts[i] = strings.Title(p)
	}
	return strings.Join(parts, "")
}

// writeAll writes all generated files to disk.
func writeAll(root string, files map[string][]byte) error {
	for path, content := range files {
		fullPath := filepath.Join(root, path)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
		if err := os.WriteFile(fullPath, content, 0644); err != nil {
			return fmt.Errorf("write %s: %w", fullPath, err)
		}
	}
	return nil
}

const capiTemplate = `// Code generated by pipewiregen. DO NOT EDIT.

package capi

import "github.com/ebitengine/purego"

{{range .Symbols}}
// {{.Name}}Func is the function type for {{.Name}}.
type {{.Name}}Func {{.Signature}}
{{end}}

var (
{{range .Symbols}}
	{{.Name}} {{.Name}}Func
{{end}}
)

func register{{.Group.Name | title}}(handle uintptr) error {
{{range .Symbols}}
	if err := purego.RegisterLibFunc(&{{.Name}}, handle, "{{.Name}}"); err != nil {
		return err
	}
{{end}}
	return nil
}
`

const portTemplate = `// Code generated by pipewiregen. DO NOT EDIT.

package out

// {{.Group.Interface}} defines the outbound interface for {{.Group.Name}} operations.
type {{.Group.Interface}} interface {
{{range .Methods}}
	{{.GoName}} {{.Signature}}
{{end}}
}
`
