// Code generated by pipewiregen. DO NOT EDIT.

package capi

import "unsafe"


// InitCAPIAdapter forwards calls to the generated CAPI variables.
type InitCAPIAdapter struct{}

func (a *InitCAPIAdapter) PWInit(argc *int32, argv ***byte) {
	pw_init(argc, argv)
}

func (a *InitCAPIAdapter) PWDeinit() {
	pw_deinit()
}


// LoopCAPIAdapter forwards calls to the generated CAPI variables.
type LoopCAPIAdapter struct{}

func (a *LoopCAPIAdapter) PWMainLoopNew(props unsafe.Pointer) unsafe.Pointer {
	return pw_main_loop_new(props)
}

func (a *LoopCAPIAdapter) PWMainLoopDestroy(loop unsafe.Pointer) {
	pw_main_loop_destroy(loop)
}

func (a *LoopCAPIAdapter) PWMainLoopRun(loop unsafe.Pointer) int32 {
	return pw_main_loop_run(loop)
}

func (a *LoopCAPIAdapter) PWMainLoopQuit(loop unsafe.Pointer) int32 {
	return pw_main_loop_quit(loop)
}

func (a *LoopCAPIAdapter) PWMainLoopGetLoop(loop unsafe.Pointer) unsafe.Pointer {
	return pw_main_loop_get_loop(loop)
}


// StreamPlaybackCAPIAdapter forwards calls to the generated CAPI variables.
type StreamPlaybackCAPIAdapter struct{}

func (a *StreamPlaybackCAPIAdapter) PWStreamNewSimple(context unsafe.Pointer, name *byte, props unsafe.Pointer, events unsafe.Pointer, data unsafe.Pointer) unsafe.Pointer {
	return pw_stream_new_simple(context, name, props, events, data)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamConnect(stream unsafe.Pointer, direction int32, id uint32, flags uint32, ports unsafe.Pointer, n_ports uint32) int32 {
	return pw_stream_connect(stream, direction, id, flags, ports, n_ports)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamSetActive(stream unsafe.Pointer, active bool) int32 {
	return pw_stream_set_active(stream, active)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamDisconnect(stream unsafe.Pointer) int32 {
	return pw_stream_disconnect(stream)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamDequeueBuffer(stream unsafe.Pointer) unsafe.Pointer {
	return pw_stream_dequeue_buffer(stream)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamQueueBuffer(stream unsafe.Pointer, buffer unsafe.Pointer) int32 {
	return pw_stream_queue_buffer(stream, buffer)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamAddListener(stream unsafe.Pointer, listener unsafe.Pointer, events unsafe.Pointer, data unsafe.Pointer) int32 {
	return pw_stream_add_listener(stream, listener, events, data)
}

func (a *StreamPlaybackCAPIAdapter) PWStreamDestroy(stream unsafe.Pointer) {
	pw_stream_destroy(stream)
}



// defaultCAPI implements the portout.CAPI composite interface by embedding
// all generated group adapters. It is constructed by newDefaultCAPI.
type defaultCAPI struct {
	InitCAPIAdapter
	LoopCAPIAdapter
	StreamPlaybackCAPIAdapter
}

// newDefaultCAPI returns a defaultCAPI whose embedded adapters forward
// every method to the corresponding generated C function variable.
func newDefaultCAPI() *defaultCAPI {
	return &defaultCAPI{}
}
