// Code generated by pipewiregen. DO NOT EDIT.

package capi

import "github.com/bnema/purego"


// pw_initFunc is the function type for pw_init.
type pw_initFunc func(argc *int32, argv ***byte)

// pw_deinitFunc is the function type for pw_deinit.
type pw_deinitFunc func()



var (

	pw_init pw_initFunc

	pw_deinit pw_deinitFunc

)

func registerInit(handle uintptr) {

	purego.RegisterLibFunc(&pw_init, handle, "pw_init")

	purego.RegisterLibFunc(&pw_deinit, handle, "pw_deinit")

}
