// Code generated by pipewiregen. DO NOT EDIT.

package capi

import "github.com/ebitengine/purego"

import "unsafe"


// pw_main_loop_newFunc is the function type for pw_main_loop_new.
type pw_main_loop_newFunc func(props unsafe.Pointer) unsafe.Pointer

// pw_main_loop_destroyFunc is the function type for pw_main_loop_destroy.
type pw_main_loop_destroyFunc func(loop unsafe.Pointer)

// pw_main_loop_runFunc is the function type for pw_main_loop_run.
type pw_main_loop_runFunc func(loop unsafe.Pointer) int32



var (

	pw_main_loop_new pw_main_loop_newFunc

	pw_main_loop_destroy pw_main_loop_destroyFunc

	pw_main_loop_run pw_main_loop_runFunc

)

func registerLoop(handle uintptr) {

	purego.RegisterLibFunc(&pw_main_loop_new, handle, "pw_main_loop_new")

	purego.RegisterLibFunc(&pw_main_loop_destroy, handle, "pw_main_loop_destroy")

	purego.RegisterLibFunc(&pw_main_loop_run, handle, "pw_main_loop_run")

}
