// Code generated by pipewiregen. DO NOT EDIT.

package capi

import "github.com/bnema/purego"

import "unsafe"


// pw_stream_new_simpleFunc is the function type for pw_stream_new_simple.
type pw_stream_new_simpleFunc func(context unsafe.Pointer, name *byte, props unsafe.Pointer, events unsafe.Pointer, data unsafe.Pointer) unsafe.Pointer

// pw_stream_connectFunc is the function type for pw_stream_connect.
type pw_stream_connectFunc func(stream unsafe.Pointer, direction int32, id uint32, flags uint32, ports unsafe.Pointer, n_ports uint32) int32

// pw_stream_set_activeFunc is the function type for pw_stream_set_active.
type pw_stream_set_activeFunc func(stream unsafe.Pointer, active bool) int32

// pw_stream_disconnectFunc is the function type for pw_stream_disconnect.
type pw_stream_disconnectFunc func(stream unsafe.Pointer) int32

// pw_stream_dequeue_bufferFunc is the function type for pw_stream_dequeue_buffer.
type pw_stream_dequeue_bufferFunc func(stream unsafe.Pointer) unsafe.Pointer

// pw_stream_queue_bufferFunc is the function type for pw_stream_queue_buffer.
type pw_stream_queue_bufferFunc func(stream unsafe.Pointer, buffer unsafe.Pointer) int32

// pw_stream_add_listenerFunc is the function type for pw_stream_add_listener.
type pw_stream_add_listenerFunc func(stream unsafe.Pointer, listener unsafe.Pointer, events unsafe.Pointer, data unsafe.Pointer) int32

// pw_stream_destroyFunc is the function type for pw_stream_destroy.
type pw_stream_destroyFunc func(stream unsafe.Pointer)



// pw_stream_events represents the callback struct for pw_stream_events.
type pw_stream_events struct{version uint32; destroy uintptr; state_changed uintptr; control_info uintptr; io_changed uintptr; param_changed uintptr; add_buffer uintptr; remove_buffer uintptr; process uintptr; drained uintptr; command uintptr; trigger_done uintptr}



var (

	pw_stream_new_simple pw_stream_new_simpleFunc

	pw_stream_connect pw_stream_connectFunc

	pw_stream_set_active pw_stream_set_activeFunc

	pw_stream_disconnect pw_stream_disconnectFunc

	pw_stream_dequeue_buffer pw_stream_dequeue_bufferFunc

	pw_stream_queue_buffer pw_stream_queue_bufferFunc

	pw_stream_add_listener pw_stream_add_listenerFunc

	pw_stream_destroy pw_stream_destroyFunc

)

func registerStream_playback(handle uintptr) {

	purego.RegisterLibFunc(&pw_stream_new_simple, handle, "pw_stream_new_simple")

	purego.RegisterLibFunc(&pw_stream_connect, handle, "pw_stream_connect")

	purego.RegisterLibFunc(&pw_stream_set_active, handle, "pw_stream_set_active")

	purego.RegisterLibFunc(&pw_stream_disconnect, handle, "pw_stream_disconnect")

	purego.RegisterLibFunc(&pw_stream_dequeue_buffer, handle, "pw_stream_dequeue_buffer")

	purego.RegisterLibFunc(&pw_stream_queue_buffer, handle, "pw_stream_queue_buffer")

	purego.RegisterLibFunc(&pw_stream_add_listener, handle, "pw_stream_add_listener")

	purego.RegisterLibFunc(&pw_stream_destroy, handle, "pw_stream_destroy")

}
