// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/purego-pipewire/pipewire"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayer creates a new instance of MockPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayer {
	mock := &MockPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayer is an autogenerated mock type for the Player type
type MockPlayer struct {
	mock.Mock
}

type MockPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayer) EXPECT() *MockPlayer_Expecter {
	return &MockPlayer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPlayer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Close() *MockPlayer_Close_Call {
	return &MockPlayer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPlayer_Close_Call) Run(run func()) *MockPlayer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Close_Call) Return(err error) *MockPlayer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Close_Call) RunAndReturn(run func() error) *MockPlayer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Pause() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockPlayer_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Pause() *MockPlayer_Pause_Call {
	return &MockPlayer_Pause_Call{Call: _e.mock.On("Pause")}
}

func (_c *MockPlayer_Pause_Call) Run(run func()) *MockPlayer_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Pause_Call) Return(err error) *MockPlayer_Pause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Pause_Call) RunAndReturn(run func() error) *MockPlayer_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockPlayer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Start() *MockPlayer_Start_Call {
	return &MockPlayer_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockPlayer_Start_Call) Run(run func()) *MockPlayer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Start_Call) Return(err error) *MockPlayer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Start_Call) RunAndReturn(run func() error) *MockPlayer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockPlayer
func (_mock *MockPlayer) State() pipewire.PlayerState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 pipewire.PlayerState
	if returnFunc, ok := ret.Get(0).(func() pipewire.PlayerState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(pipewire.PlayerState)
	}
	return r0
}

// MockPlayer_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockPlayer_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) State() *MockPlayer_State_Call {
	return &MockPlayer_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockPlayer_State_Call) Run(run func()) *MockPlayer_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_State_Call) Return(playerState pipewire.PlayerState) *MockPlayer_State_Call {
	_c.Call.Return(playerState)
	return _c
}

func (_c *MockPlayer_State_Call) RunAndReturn(run func() pipewire.PlayerState) *MockPlayer_State_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockPlayer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Stop() *MockPlayer_Stop_Call {
	return &MockPlayer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockPlayer_Stop_Call) Run(run func()) *MockPlayer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Stop_Call) Return(err error) *MockPlayer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Stop_Call) RunAndReturn(run func() error) *MockPlayer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
