// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/purego-pipewire/pipewire"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRuntime creates a new instance of MockRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntime {
	mock := &MockRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuntime is an autogenerated mock type for the Runtime type
type MockRuntime struct {
	mock.Mock
}

type MockRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntime) EXPECT() *MockRuntime_Expecter {
	return &MockRuntime_Expecter{mock: &_m.Mock}
}

// Deinit provides a mock function for the type MockRuntime
func (_mock *MockRuntime) Deinit() {
	_mock.Called()
	return
}

// MockRuntime_Deinit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deinit'
type MockRuntime_Deinit_Call struct {
	*mock.Call
}

// Deinit is a helper method to define mock.On call
func (_e *MockRuntime_Expecter) Deinit() *MockRuntime_Deinit_Call {
	return &MockRuntime_Deinit_Call{Call: _e.mock.On("Deinit")}
}

func (_c *MockRuntime_Deinit_Call) Run(run func()) *MockRuntime_Deinit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRuntime_Deinit_Call) Return() *MockRuntime_Deinit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRuntime_Deinit_Call) RunAndReturn(run func()) *MockRuntime_Deinit_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type MockRuntime
func (_mock *MockRuntime) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuntime_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockRuntime_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockRuntime_Expecter) Init() *MockRuntime_Init_Call {
	return &MockRuntime_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockRuntime_Init_Call) Run(run func()) *MockRuntime_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRuntime_Init_Call) Return(err error) *MockRuntime_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuntime_Init_Call) RunAndReturn(run func() error) *MockRuntime_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMainLoop provides a mock function for the type MockRuntime
func (_mock *MockRuntime) NewMainLoop() (pipewire.MainLoop, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewMainLoop")
	}

	var r0 pipewire.MainLoop
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (pipewire.MainLoop, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() pipewire.MainLoop); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipewire.MainLoop)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuntime_NewMainLoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMainLoop'
type MockRuntime_NewMainLoop_Call struct {
	*mock.Call
}

// NewMainLoop is a helper method to define mock.On call
func (_e *MockRuntime_Expecter) NewMainLoop() *MockRuntime_NewMainLoop_Call {
	return &MockRuntime_NewMainLoop_Call{Call: _e.mock.On("NewMainLoop")}
}

func (_c *MockRuntime_NewMainLoop_Call) Run(run func()) *MockRuntime_NewMainLoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRuntime_NewMainLoop_Call) Return(mainLoop pipewire.MainLoop, err error) *MockRuntime_NewMainLoop_Call {
	_c.Call.Return(mainLoop, err)
	return _c
}

func (_c *MockRuntime_NewMainLoop_Call) RunAndReturn(run func() (pipewire.MainLoop, error)) *MockRuntime_NewMainLoop_Call {
	_c.Call.Return(run)
	return _c
}
