// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMainLoop creates a new instance of MockMainLoop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMainLoop(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMainLoop {
	mock := &MockMainLoop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMainLoop is an autogenerated mock type for the MainLoop type
type MockMainLoop struct {
	mock.Mock
}

type MockMainLoop_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMainLoop) EXPECT() *MockMainLoop_Expecter {
	return &MockMainLoop_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function for the type MockMainLoop
func (_mock *MockMainLoop) Destroy() {
	_mock.Called()
	return
}

// MockMainLoop_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockMainLoop_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockMainLoop_Expecter) Destroy() *MockMainLoop_Destroy_Call {
	return &MockMainLoop_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockMainLoop_Destroy_Call) Run(run func()) *MockMainLoop_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMainLoop_Destroy_Call) Return() *MockMainLoop_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMainLoop_Destroy_Call) RunAndReturn(run func()) *MockMainLoop_Destroy_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockMainLoop
func (_mock *MockMainLoop) Run() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockMainLoop_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockMainLoop_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockMainLoop_Expecter) Run() *MockMainLoop_Run_Call {
	return &MockMainLoop_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockMainLoop_Run_Call) Run(run func()) *MockMainLoop_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMainLoop_Run_Call) Return(n int32) *MockMainLoop_Run_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMainLoop_Run_Call) RunAndReturn(run func() int32) *MockMainLoop_Run_Call {
	_c.Call.Return(run)
	return _c
}
