// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlaybackStream creates a new instance of MockPlaybackStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaybackStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaybackStream {
	mock := &MockPlaybackStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaybackStream is an autogenerated mock type for the PlaybackStream type
type MockPlaybackStream struct {
	mock.Mock
}

type MockPlaybackStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaybackStream) EXPECT() *MockPlaybackStream_Expecter {
	return &MockPlaybackStream_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPlaybackStream
func (_mock *MockPlaybackStream) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaybackStream_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPlaybackStream_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPlaybackStream_Expecter) Close() *MockPlaybackStream_Close_Call {
	return &MockPlaybackStream_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPlaybackStream_Close_Call) Run(run func()) *MockPlaybackStream_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaybackStream_Close_Call) Return(err error) *MockPlaybackStream_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaybackStream_Close_Call) RunAndReturn(run func() error) *MockPlaybackStream_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockPlaybackStream
func (_mock *MockPlaybackStream) Write(samples [][]float32) error {
	ret := _mock.Called(samples)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([][]float32) error); ok {
		r0 = returnFunc(samples)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaybackStream_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockPlaybackStream_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - samples [][]float32
func (_e *MockPlaybackStream_Expecter) Write(samples interface{}) *MockPlaybackStream_Write_Call {
	return &MockPlaybackStream_Write_Call{Call: _e.mock.On("Write", samples)}
}

func (_c *MockPlaybackStream_Write_Call) Run(run func(samples [][]float32)) *MockPlaybackStream_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [][]float32
		if args[0] != nil {
			arg0 = args[0].([][]float32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaybackStream_Write_Call) Return(err error) *MockPlaybackStream_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaybackStream_Write_Call) RunAndReturn(run func(samples [][]float32) error) *MockPlaybackStream_Write_Call {
	_c.Call.Return(run)
	return _c
}
