// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/purego-pipewire/pipewire"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayer creates a new instance of MockPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayer {
	mock := &MockPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayer is an autogenerated mock type for the Player type
type MockPlayer struct {
	mock.Mock
}

type MockPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayer) EXPECT() *MockPlayer_Expecter {
	return &MockPlayer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPlayer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Close() *MockPlayer_Close_Call {
	return &MockPlayer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPlayer_Close_Call) Run(run func()) *MockPlayer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Close_Call) Return(err error) *MockPlayer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Close_Call) RunAndReturn(run func() error) *MockPlayer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewStream provides a mock function for the type MockPlayer
func (_mock *MockPlayer) NewStream(ctx context.Context, format pipewire.AudioFormat) (pipewire.PlaybackStream, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for NewStream")
	}

	var r0 pipewire.PlaybackStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pipewire.AudioFormat) (pipewire.PlaybackStream, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pipewire.AudioFormat) pipewire.PlaybackStream); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipewire.PlaybackStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pipewire.AudioFormat) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayer_NewStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStream'
type MockPlayer_NewStream_Call struct {
	*mock.Call
}

// NewStream is a helper method to define mock.On call
//   - ctx context.Context
//   - format pipewire.AudioFormat
func (_e *MockPlayer_Expecter) NewStream(ctx interface{}, format interface{}) *MockPlayer_NewStream_Call {
	return &MockPlayer_NewStream_Call{Call: _e.mock.On("NewStream", ctx, format)}
}

func (_c *MockPlayer_NewStream_Call) Run(run func(ctx context.Context, format pipewire.AudioFormat)) *MockPlayer_NewStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pipewire.AudioFormat
		if args[1] != nil {
			arg1 = args[1].(pipewire.AudioFormat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayer_NewStream_Call) Return(playbackStream pipewire.PlaybackStream, err error) *MockPlayer_NewStream_Call {
	_c.Call.Return(playbackStream, err)
	return _c
}

func (_c *MockPlayer_NewStream_Call) RunAndReturn(run func(ctx context.Context, format pipewire.AudioFormat) (pipewire.PlaybackStream, error)) *MockPlayer_NewStream_Call {
	_c.Call.Return(run)
	return _c
}
